### ISSUE TITLE
[DOC] Accessibility issues in dark mode

### ISSUE THREAD

**Issue by mwcraig** [GeminiDRSoftware/astrodata#29]
Thank you for submitting an issue related to our documentation! *If this is a minor change or something you are willing to modify directly yourself, your help would be greatly appreciated!* Please modify the file using your preferred method (e.g., [directly in github](https://docs.github.com/en/repositories/working-with-files/managing-files/editing-files) or by [making a pull request](https://docs.github.com/en/pull-requests/collaborating-with-pull-requests/proposing-changes-to-your-work-with-pull-requests/creating-a-pull-request)). Otherwise, continue on with this form.

## Description

There are a few issues with the documentation when viewed in dark mode. 

1. Class names cannot be read because they are in black text (pic 1 below)
2. The python prompts very hard to see in dark mode (see pic 2 below)
3. Whether class and function names can be read depends a lot on screen brightness (see pic 2 below). On my laptop screen on battery power while riding in a vehicle during the daytime they were really hard to read. On the monitor of my home computer or if I turned up the brightness of the laptop screen I could see them.

### Pic 1

<img width="784" alt="Reference_API_—_astrodata_0_0_0_documentation" src="https://github.com/user-attachments/assets/cabc7f27-2fff-4b1c-8c55-f7648ec39bf5">

### Pic 2

<img width="502" alt="👀_astrodata_review" src="https://github.com/user-attachments/assets/39a84a0a-6c21-43bd-be39-6e45189bd25a">

## Solution

One short term fix would be to disable dark mode if possible. An alternative is to check whether there is additional css for dark mode that should be applied to your code snippets.

### Urgency
- [ ] This problem should be fixed quickly (urgent)
- [ ] This problem is minor/does not require immediate fixing.

**Comment by teald** [comment]
There is an issue about this with the dark theme we use, but it's not been worked on yet as far as I can tell.
+ https://github.com/MrDogeBro/sphinx_rtd_dark_mode/issues/27

It is probably best to add some CSS or find another theme, as suggested. Thanks for catching this (especially the class names in the API reference)! I'm surprised I hadn't yet, given I mostly use dark mode 😅
